eureka:
  client:
    serviceUrl:
      defaultZone       : http://localhost:9001/eureka/
server:
  port                  : 9002
#  port                  : 9003

spring:
  application:
    name                : eureka-service
  zipkin:
    base-url            : http://localhost:9006