eureka:
  client:
    serviceUrl:
      defaultZone         : http://localhost:9001/eureka/
server:
  port                    : 9004
  contextPath             : /feign
  servlet-path            : /feign
spring:
  application:
    name                  : feign-service

feign:
  hystrix:
    enabled               : true